base_url = "https://resume.ianmontgomery.net"
title = "Ian Montgomery - Infrastructure Engineer"
description = "Infrastructure Engineer with a proven track record of driving operational excellence and rapid software delivery. I have worked with companies such as Xero, EndGame, and Epi-interactive."
compile_sass = false
build_search_index = false
generate_feeds = false

taxonomies = []

[extra]
og_description = "Infrastructure Engineer with a proven track record of driving operational excellence and rapid software delivery. Combining leadership experience across multiple industries with a passion for technology."
